### ISSUE TITLE
Build Tram Geo Info for position tracking

### ISSUE THREAD

**Issue by dfAndrade** [dfAndrade/tram-lx#1]
- [ ] Retrieve geopkg with lines
- [ ] Edit raw line info with station position for segmentation
- [ ] Label segments ("A-B" segment from station A to station B)
